---
name: Build

on:
  push:
    paths:
      - '**.ino'
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - '**.ino'
      - '.github/workflows/*.yml'

jobs:
  cpplint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install cpplint
        run: pip3 install cpplint
      - name: Add .local/bin to path
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Run cpplint
        run: make lint
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
      - name: Initialize Arduino CLI configuration
        run: arduino-cli config init
      - name: Install M5Stack platform
        run: make platform
      - name: Install libraries
        run: make libraries
      - name: Install pyserial
        run: pip3 install pyserial
      - name: Compile Sketch
        run: make build
