---
name: Build

on:
  push:
    paths:
      - '**.ino'
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - '**.ino'
      - '.github/workflows/*.yml'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run arduino-lint
        uses: arduino/arduino-lint-action@v1
        with:
          compliance: strict
      - name: Run clang-format
        run: |
          sudo apt update
          sudo apt install clang-format
          make lint
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
      - name: Initialize Arduino CLI configuration
        run: arduino-cli config init
      - name: Install M5Stack platform
        run: make platform
      - name: Install libraries
        run: make libraries
      - name: Install requirements
        run: make requirements
      - name: Compile Sketch
        run: make build
